### ISSUE TITLE
Using S2Loop to get covering

### ISSUE THREAD

**Issue by chochim** [micolous/s2-geometry-library#10]
I have two functions which I am using to get a covering of a polygon. The functions are as follows:
```
def get_lat_lng(coordinate):
    return  S2LatLng.FromDegrees(coordinate[1],coordinate[0]).Normalized().ToPoint()
```
```
def get_tiles_from_polygon(lst_of_coords):
    """
    Given a polygon in form of a lat-lng loop, returns  a
    set of tiles which are contained inside this polygon.
    The set of files will vary in size as per the level.
    :param lst_of_coords: The coordinates which define the polygon boundary loop ( [[lng1,lat1] , [lng2,lat2]...] )
    :return: list of tile ids
    """
    #given a polygon, return the containing tiles
    #first convert the coordinate list into lat/lngs
    poly_coords = map(get_lat_lng, lst_of_coords)
    print type(poly_coords[0]) #this is a SwigPyObject and not S2Point object
    coverer = S2RegionCoverer()
    coverer.set_max_level(17)
    coverer.set_min_level(14)
    coverer.set_max_cells(10000)
    point_vector = S2PointVector(poly_coords)
    polygon_region = S2Loop(point_vector) #--> ERROR
    return coverer.GetCovering(polygon_region)
```
When I run the code, I get the following error:
```
Traceback (most recent call last):
  File "exp1.py", line 101, in <module>
    cell_obj = get_tiles_from_polygon(list_of_coordinates)
  File "exp1.py", line 91, in get_tiles_from_polygon
    polygon_region = S2Loop(point_vector)
  File "/Library/Python/2.7/site-packages/s2/s2.py", line 1647, in __init__
    this = _s2.new_S2Loop(*args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'new_S2Loop'.
  Possible C/C++ prototypes are:
    S2Loop::S2Loop()
    S2Loop::S2Loop(vector< S2Point > const &)
    S2Loop::S2Loop(S2Cell const &)
```
Is this functionality implemented? If so, shouldnt the type be of S2Point and not SwigPyObject?

**Comment by micolous** [comment]
I also attempted this and gave up using Python for the task.

There is something strange going on in SWIG land, and it was quicker for me to write something in C++ to do the same thing than to try to make SWIG work properly.  I did expend a significant effort to attempt to make SWIG play nice, but in the end got nowhere.

The code I wrote in C++ is here:
https://github.com/micolous/maptz/blob/master/geojson_to_s2.cc

This will use libgdal to read a shapefile, and then turn polygons into an S2Loop..

There's a significant amount of warnings relating to C++11 issues which I want to have a look at addressing before having another look at the SWIG problems, because fixing those may make it easier.

**Comment by chochim** [comment]
@micolous - Thanks for the response. I guess, it was easier to write the code in Java/C++ then to get it working in python.

**Comment by micolous** [comment]
Yeah, sorry.  I'm kinda stuck here.

One other alternative is if your inputs are "simple" types in Python, you can write a Python extension to do the gory S2 bits, and then pass the result back to Python.

**Comment by MateoTTR** [comment]
Hi there,
I ran into the same problem. I am afraid this will prevent me from using the python bindings of the s2 library for now... I am not familiar with how SWIG works in general, but C++ API with direct references to C++ objects are not properly wrapped (how the hell could I pass a vecto<T> const & from Python?)
Would be curious to see how this can be worked around.
